export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const USER_INFOS_SUCCESS = "USER_INFOS_SUCCESS";
export const USER_INFOS_FAIL = "USER_INFOS_FAIL";

export const SET_INFOS_SUCCESS = "SET_INFOS_SUCCESS";
export const SET_INFOS_FAIL = "SET_INFOS_FAIL";