swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints for part 2 (Transactions)
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: All bank accounts of the user
      description: API for fetching all bank accounts
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Bank accounts fetching successfully
          schema:
            $ref: '#/definitions/AccountResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Transactions not found
        '500':
          description: Internal Server Error
  /user/{idAccount}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: All transactions of bank account
      description: API for fetching bank accounts and its transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: idAccount
          description: id of the bank account
          required: true
          type: integer
        - in: body
          name: body
          description: list of transactions between start date and end date
          required: true
          schema:
            $ref: '#/definitions/dateTransactions'
      produces:
        - application/json
      responses:
        '200':
          description: list of transactions fetching Successfully
          schema:
            $ref: '#/definitions/transactionsResponseList'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Account not found
        '500':
          description: Internal Server Error
  /user/transaction:
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Add transaction
      description: for addind new transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: information required for adding a new transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionWithoutId'
      produces:
        - application/json
      responses:
        '200':
          description: transaction added successfully
          schema:
            $ref: '#/definitions/transactionsResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /user/{idTransaction}:
    put:
      security:
          - Bearer: []
      tags:
        - Transaction Module
      summary: Updating transaction
      description: API for updating a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: idTransaction
          description: id transaction
          required: true
          type: integer
        - in: body
          name: body
          description: Update transaction attributes
          required: true
          schema:
            $ref: '#/definitions/editTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: transaction updated successully
          schema:
            $ref: '#/definitions/transactionsResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        "404":
          description: Transaction not found
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Delete transaction
      description: API for deleting a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: idTransaction
          description: id transaction
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: transaction deleted successully
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        "404":
          description: Transaction not found
        '500':
          description: Internal Server Error
      
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  dateTransactions:
    properties:
      start_date:
        type: string
        description: start date
      end_date:
        type: string
        description: end date
  AccountResponse:
    type: object
    properties:
      id:
        type: integer
      id_transactions:
        type: array
        items:
          type: integer
      current_balance:
        type: integer
      title:
        type: string
  transactionsResponse:
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: integer
          id_compte:
            type: integer
          date:
            type: string
          amount:
            type: integer
          balance:
            type: integer
          transaction_type:
            type: string
          Category: 
            type: string
          Notes:
            type: string
  transactionsResponseList:
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
            id_compte:
              type: integer
            date:
              type: string
            amount:
              type: integer
            balance:
              type: integer
            transaction_type:
              type: string
            Category: 
              type: string
            Notes:
              type: string
  
  TransactionWithoutId:
    type: object
    properties:
      id_compte:
        type: integer
      date:
        type: string
      amount:
        type: integer
      balance:
        type: integer
      transaction_type:
        type: string
      Category: 
        type: string
      Notes:
        type: string
  editTransaction:
    properties:
      category:
        type: string
        description: updating category
      notes:
        type: string
        description: updating notes
      
      
      
